from test_sqlite import *

dob_tr = ultimate_data_dict['dob_tr']
age = ultimate_data_dict['age']
i = len(age)
#print(i)
geee = (dob_tr[i]-age[i]*365 for i in range(i))
print(next(geee))
print(next(geee))
print(next(geee))
print(next(geee))
print(next(geee))
print(next(geee))
print(next(geee))
print(next(geee))
print(next(geee))
print(next(geee))
print(next(geee))
print(next(geee))
print(next(geee))
print(next(geee))
print(next(geee))
print(next(geee))
print(next(geee))
print(next(geee))
print(next(geee))
print(next(geee))
print(next(geee))
print(next(geee))
print(next(geee))
print(next(geee))
print(next(geee))
print(next(geee))
print(next(geee))
print(next(geee))
print(next(geee))
print(next(geee))
print(next(geee))
print(next(geee))
print(next(geee))
print(next(geee))
print(next(geee))
print(next(geee))
print(next(geee))
print(next(geee))
print(next(geee))
print(next(geee))
print(next(geee))
print(next(geee))
print(next(geee))
print(next(geee))
print(next(geee))
